# Generated by Django 6.1 on 2026-08-19 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=100)),
                ('prueba', models.CharField(max_length=100)),
                ('fecha_prueba', models.DateField()),
                ('nivel_conocimiento', models.IntegerField(choices=[(1, 'Nada (0-20%)'), (2, 'Poco (20-40%)'), (3, 'Medio (40-60%)'), (4, 'Bien (60-80%)'), (5, 'Dominado (80-100%)')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SesionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('completado', models.BooleanField(default=False)),
                ('minutos_estimados', models.IntegerField(default=45)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='inicio.evaluacion')),
            ],
        ),
    ]
